#!/bin/bash
#
# Copyright (c) 2021-present BPPTKG
#
# Project repository: https://github.com/bpptkg/bulletin
#
# Send WEBOBS_HIDE_EVENT or WEBOBS_RESTORE_EVENT to the bulletin web services
# using bpptkg-bulletinclient library.
#
# For WEBOBS_HIDE_EVENT, required payload is event ID (eventid). Operator name
# can also be specified.
#
# For WEBOBS_RESTORE_EVENT, required payloads are event ID (eventid) and event
# type (eventtype). Operator name can also be specified.
#
# Arguments:
#
# $1 -> Event ID (eventid), e.g. 2021-07#3414.
#
# $2 -> Event type (eventtype), e.g. VTA, VTB.
#
# $3 -> Operator name, e.g. YUL.
#

if [ $2 == 'NULL' ]; then
    echo -e "\nEvent modified at $(date "+%Y-%m-%d %H:%M:%S UTC"). Action: WEBOBS_HIDE_EVENT, Event ID: $1, Operator: $3."

    bulletinclient WEBOBS_HIDE_EVENT --eventid "$1" --operator $3
else
    echo -e "\nEvent modified at $(date "+%Y-%m-%d %H:%M:%S UTC"). Action: WEBOBS_RESTORE_EVENT, Event ID: $1, Event type: $2, Operator: $3."

    bulletinclient WEBOBS_RESTORE_EVENT --eventid "$1" --eventtype $2 --operator $3
fi
