services:
  - name: mysql:5.7
    alias: mysql-seismic_bulletin
  - name: mysql:5.7
    alias: mysql-bulletin
  - redis:latest

variables:
  MYSQL_DATABASE: "bulletin_test"
  MYSQL_ROOT_PASSWORD: "test"

stages:
  - test

before_script:
  - apt-get update -qy
  - apt-get install -y python3-pip
  - pip install tox

python36:
  image: python:3.6
  stage: test
  script: tox -e py36

python37:
  image: python:3.7
  stage: test
  script: tox -e py37

python38:
  image: python:3.8
  stage: test
  script: tox -e py38

python39:
  image: python:3.9
  stage: test
  script: tox -e py39
